# Generated by Django 5.0.4 on 2024-04-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OPENING', 'Opening'), ('QUESTIONING', 'Questioning'), ('PRESENTING', 'Presenting'), ('CLOSING_OUTCOME', 'Closing & Outcome')], max_length=20, unique=True)),
                ('definition', models.TextField()),
                ('prompt', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
