# Generated by Django 5.0.4 on 2024-04-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_statementtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementtype',
            old_name='instructions',
            new_name='instruction',
        ),
    ]
