# Generated by Django 5.0.4 on 2024-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_rename_instructions_statementtype_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementtype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
