# Generated by Django 5.0.4 on 2024-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_statementclassificationtypeprompt_invalid_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='docker_feteched',
            field=models.BooleanField(default=False),
        ),
    ]
