# Generated by Django 5.0.4 on 2024-04-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_llmmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='model_llm',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
