# Generated by Django 5.0.3 on 2024-04-28 18:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_classification_model_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='segments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
