# Generated by Django 5.0.4 on 2024-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_classification_segment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OPENING', 'Opening'), ('QUESTIONING', 'Questioning'), ('PRESENTING', 'Presenting'), ('CLOSING_OUTCOME', 'Closing & Outcome')], max_length=20, unique=True)),
                ('definition', models.TextField()),
                ('prompt', models.TextField()),
                ('examples', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='classification',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
