# Generated by Django 5.0.4 on 2024-05-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_rename_definition_statementlevel_evaluation_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementlevel',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
