# Generated by Django 5.0.4 on 2024-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_statementlevel_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='probability',
        ),
        migrations.AddField(
            model_name='classification',
            name='confidence_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='reason_for_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
