# Generated by Django 5.0.4 on 2024-05-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_remove_classification_probability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementtype',
            old_name='instruction',
            new_name='examples',
        ),
        migrations.RemoveField(
            model_name='statementtype',
            name='prompt',
        ),
    ]
