# Generated by Django 5.0.4 on 2024-05-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_finalstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalstatement',
            name='category',
            field=models.CharField(choices=[('OPENING', 'Opening'), ('QUESTIONING', 'Questioning'), ('PRESENTING', 'Presenting'), ('CLOSING', 'Closing'), ('OUTCOME', 'Outcome')], max_length=20),
        ),
    ]
