# Generated by Django 5.0.4 on 2024-05-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_alter_statementlevel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalStatement',
            new_name='FinalStatementWithLevel',
        ),
        migrations.RenameModel(
            old_name='Classification',
            new_name='StatementClassification',
        ),
        migrations.RenameModel(
            old_name='StatementType',
            new_name='StatementClassificationTypePrompt',
        ),
        migrations.RenameModel(
            old_name='StatementLevel',
            new_name='StatementLevelPrompt',
        ),
    ]
